{
  "openapi": "3.0.0",
  "info": {
    "title": "ImobiManager - API",
    "version": "3.0.0",
    "description": "Documentação da API do ImobiManager"
  },
  "servers": [
    {
      "url": "http://localhost:3000",
      "description": "Local server"
    }
  ],
  "tags": [
    {
      "name": "User",
      "description": "Operations related to user management"
    }
  ],
  "paths": {
    "/signup": {
      "post": {
        "tags": ["User"],
        "summary": "Nova conta",
        "description": "Cria uma nova conta de usuário",
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/NewUser"
              },
              "examples": {
                "newUser": {
                  "summary": "Exemplo de novo usuário",
                  "value": {
                    "firstName": "John",
                    "lastname": "Doe",
                    "email": "john.doe@example.com",
                    "password": "password123",
                    "confirm": "password123"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "User created successfully",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/User"
                },
                "examples": {
                  "user": {
                    "summary": "Exemplo de resposta de usuário",
                    "value": {
                      "id": 1,
                      "firstName": "John",
                      "lastname": "Doe",
                      "email": "john.doe@example.com"
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Invalid input",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                },
                "examples": {
                  "error": {
                    "summary": "Exemplo de resposta de erro",
                    "value": {
                      "message": "Invalid input data"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/signin": {
      "post": {
        "tags": ["User"],
        "summary": "Login",
        "description": "Faz login na conta do usuário",
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Login"
              },
              "examples": {
                "login": {
                  "summary": "Exemplo de login",
                  "value": {
                    "email": "john.doe@example.com",
                    "password": "password123"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "User logged in successfully",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/User"
                },
                "examples": {
                  "user": {
                    "summary": "Exemplo de resposta de usuário",
                    "value": {
                      "id": 1,
                      "firstName": "John",
                      "lastname": "Doe",
                      "email": "john.doe@example.com"
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Invalid input",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                },
                "examples": {
                  "error": {
                    "summary": "Exemplo de resposta de erro",
                    "value": {
                      "message": "Invalid email or password"
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "NewUser": {
        "type": "object",
        "properties": {
          "firstName": {
            "type": "string"
          },
          "lastname": {
            "type": "string"
          },
          "email": {
            "type": "string"
          },
          "password": {
            "type": "string"
          },
          "confirm": {
            "type": "string"
          }
        },
        "required": ["firstName", "lastname", "email", "password", "confirm"]
      },
      "Login": {
        "type": "object",
        "properties": {
          "email": {
            "type": "string"
          },
          "password": {
            "type": "string"
          }
        },
        "required": ["email", "password"]
      },
      "User": {
        "type": "object",
        "properties": {
          "id": {
            "type": "integer"
          },
          "firstName": {
            "type": "string"
          },
          "lastname": {
            "type": "string"
          },
          "email": {
            "type": "string"
          }
        }
      },
      "Error": {
        "type": "object",
        "properties": {
          "message": {
            "type": "string"
          }
        }
      }
    }
  }
}